### ISSUE TITLE
DelphiLint fails when Delphi 11 is not installed

### ISSUE THREAD

**Issue by mobius1qwe** [integrated-application-development/delphilint#10]
### Prerequisites

- [X] This bug is in DelphiLint, not SonarDelphi, SonarQube, or my Delphi code.
- [X] This bug has not already been reported.

### Delphi IDE version

12 Athens

### DelphiLint version

1.0 Latest release

### SonarDelphi version

1.3.0 default version

### Issue description

![image](https://github.com/integrated-application-development/delphilint/assets/26689802/61d7b3af-8304-4093-ae2f-da930c1415e6)
I have multiple delphi versions installed and I just 
- ran the install.bat, 
- opened a random project and 
- tried to run it, 
- error happens. 

I have PATH overrides on Delphi IDE since its mandatory when you have multiple versions installed. Maybe DL isn't reading from that but is reading from windows' Path instead.

### Steps to reproduce

- ran the install.bat, 
- opened a random project and 
- tried to run it, 
- error happens.

**Comment by fourls** [comment]
Hi, thanks for raising this issue.

This is caused by a silly typo - when DelphiLint tells SonarDelphi where the installation is, instead of setting `sonar.delphi.installationPath`, DelphiLint sets `sonar.delphi.bds.path` instead (the old name of the property). Since the property is unset, SonarDelphi defaults to the Delphi 11 installation path, hence this error when Delphi 11 is not installed.

That has stayed hidden for months because I have both Delphi 11 and Delphi 12 installed - I will fix this today and release a new patch version. 

DelphiLint should work perfectly when multiple IDE versions are installed - there has been care to support that use case since we know it's a common one.

**Comment by fourls** [comment]
This issue is now resolved in [DelphiLint 1.0.1](https://github.com/integrated-application-development/delphilint/releases/tag/v1.0.1).
