### ISSUE TITLE
possibility to disable or alter rules?

### ISSUE THREAD

**Issue by Khorkhe** [integrated-application-development/delphilint#15]
### Prerequisites

- [X] This question has not already been answered.
- [X] This question is about DelphiLint, not SonarDelphi, SonarQube, or Delphi.

### Inquiry

is there a plan to list the available rules, potentially deselecting the ones which are not of current high importance?
in my case, my local variables start with a lowercase so I am bombarded with PascalCase warnings.

**Comment by fourls** [comment]
Hi @Khorkhe, since there's been a number of [requests](https://en.delphipraxis.net/topic/11266-delphilint-v100-released/?do=findComment&comment=89456) to be able to configure rules in standalone mode, I think this would be a good feature to add - I've just opened #16 to track progress on this. If you have any thoughts, feel free to discuss on that issue!

If you're using connected mode, you can already configure rules via SonarQube - the relevant section of the SonarDelphi manual is [here](https://github.com/integrated-application-development/sonar-delphi/blob/master/docs/MANUAL.md#configure-analysis-rules).
