### ISSUE TITLE
New installation; standalone mode

### ISSUE THREAD

**Issue by wmeyer48** [integrated-application-development/delphilint#26]
### Prerequisites

- [X] This bug is in DelphiLint, not SonarQube or the Delphi IDE.
- [X] This bug has not already been reported.
- [X] This bug is not a problem related to analysis quality (e.g. parsing errors, false positive issues), which should be raised on the [SonarDelphi repository](https://github.com/integrated-application-development/sonar-delphi/issues).

### Delphi IDE version

Delphi 11.3 Enterprise Version 28.0.47991.2819

### DelphiLint version

1.0.2

### SonarDelphi version

1.4.0

### Issue description

I installed JRE 1.8, as Java was not in my VM. On installing DelphiLint, it wanted me to set external resurces. The JRE installation did not set JAVA_HOME, and I had no idea what it should be set to, nor did I find any explanation of this issue in the readme. I did finally point it at java.exe in the JRE.
When I attempt to analyze a file, I get an error message: There was a problem reaching the DelphiLint server. Server failed to communicate port.

### Steps to reproduce

In a system or VM with no Java and no DelphiLint present:

1. Install JRE 1.8.
2. Install DelphiLint. 
3. Set external resources; point to java.exe in the JRE.
4. Open a Delphi project.
5. Open a module in the project.
6. With DelphiLint, Analyze This File
7. Observe error described above

**Comment by fourls** [comment]
Hi @wmeyer48, 

> I installed JRE 1.8, as Java was not in my VM. 

DelphiLint requires Java 11 or above, as mentioned prominently in the README and the "External Resources Setup" form.

JRE 1.8 (aka Java 8) was released ten years ago and has since been superseded by 14 major versions. Java 11 (released 2018) is the next long term support (LTS) version after Java 8, and is the earliest supported version for DelphiLint.

This would be why your server is not starting. Please ensure that all prerequisites are installed to at least the minimum supported version, as described in the README. If you are still encountering problems after doing this, please raise another issue.

**Comment by wmeyer48** [comment]
Thank you, and sorry. Went to Oracle, it presented that version
prominently. Will try again.

Bill
